export const localStorageKey = {
  auth_key: "auth_key",
  designation_id: "designation_id",
  adminDetail:"adminDetail",
  vendorId: "vendor_id",
  productTable: "product_table",
  customerTable: "customer_table",
  vendorTable: "vendor_table",
  categoryTable: "category_table",
  adminCatTable: "admin_cat_table",
  variantTable: "variant_table",
  blogTable: "blog_table",
  couponTable:"coupon_table",
  promotionalOfferTable: "promotional_offer_table",
  giftCardTable: "gift_card_table",
  giftCardCategoryTable: "gift_card_category_table",
  monthlyReportTable: "monthly_report_table",
  affliateUserTable: "affliate_user_table",
  policyTable:"policyTable",
  SalesAndTrafficReportTable:'SalesAndTrafficReportTable',
  ShopSaleReportTable:'ShopSaleReportTable',
  SalesAndTrafficByChildItemReportTable:'SalesAndTrafficByChildItemReportTable',
  SalesAndTrafficByParentItemReportTable:'SalesAndTrafficByParentItemReportTable',
  NewUsersReportTable:'NewUsersReportTable',
  CustomerReportTable:'CustomerReportTable',
  GiftCardReportTable:'GiftCardReportTable',
  storeTable:"StoreTable",
  productReport:"productReport",
  shopReport:"shopReport",
  voucherTable:"voucherTable"
};
